languageCode = "en"
languageName = "EN"
weight = 20
title = "Logit Studio"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2006-01-02 (Mon)"
  description = "GOODJINCâ€™s Archive: Believing in the power of records."

[params.author]
  name = "GOODJINC"
  email = "hello@goodjinc.com"
  image = "img/author.jpg"
  headline = "Little by little, one travels far"
  bio = "Little by little, one travels far"
  links = [
    { email = "mailto:hello@goodjinc.com" },
    { github = "https://github.com/goodjinc" },
  ]